---
version: '3'

services:
  privy:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      SERVER_ADDRESS: ":8080"
      LOG_LEVEL: "debug"
      LOGGER_FORMAT: "text"
      DATABASE_HOST: "postgres"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "root"
      DATABASE_NAME: "privy"
      DATABASE_PORT: 5432
      DATABASE_ENABLE_LOG: "false"
      DATABASE_MAX_IDLE_CONN: 2
      DATABASE_MAX_OPEN_CONN: 10
    ports:
      - 8080:8080
    expose:
      - 8080
    links:
      - postgres:postgres
    depends_on:
      - wait-for-it

  wait-for-it:
    image: willwill/wait-for-it
    command: ["postgres:5432 -t 60 -- echo postgres is up"]
    links:
      - postgres:postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_DB: "privy"
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "postgres"
